name: GitHub Issues Git Notes
description: Stores GitHub Issues in Git notes on every push to the repository.
runs:
  using: composite
  steps:
  - name: Check out the Git repository workflow ref (detached HEAD)
    uses: actions/checkout@v3
  - name: Run the action script
    shell: bash
    run: |
      # Configure GitHub Actions service account Git identity
      git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      git config --global user.name "github-actions[bot]"
      
      # Store the GitHub Issues in a Git note associated to the main branch
      git notes add main -f -m "$(curl --no-progress-meter '${{github.api_url}}/repos/${{github.repository}}/issues?state=all' -u :${{github.token}})"

      # Push the changes to the Git notes back to the GitHub repository
      git push origin refs/notes/* -f
